services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "${PORT:-8081}:8081"
    command: sh -lc "npm ci || npm install --legacy-peer-deps && npx vue-cli-service serve --host 0.0.0.0 --port ${PORT:-8081}"
volumes:
  node_modules:
